### ISSUE TITLE
Locally stored information found. Ignore and refresh from internet

### ISSUE THREAD

**Issue by akhlan** [xbmc/translations#10]
Hi,

I’m a french user with a translation issue…

In the translation file (https://github.com/xbmc/translations/blob/master/kodi-translations/kodi-main/.httpcache/TRX/kodi-main/kodi.core/fr_FR/strings.po) , we have this sequence

> msgctxt "#20446"
> msgid "Locally stored information found. Ignore and refresh from Internet?"
> msgstr “Informations trouvées localement.\nFaut-il ignorer et actualiser depuis Internet ?”

but the \n isn’t recognyzed and on the screen, we have only “Informations trouvées localement.” how change the \n and by what to have

> Informations trouvées localement.
> Faut-il ignorer et actualiser depuis Internet ?

Rgds

**Comment by MartijnKaijser** [comment]
You don't use \n at all unless it's in the original text.
