### ISSUE TITLE
Difference between #14061 and #16316 ?

### ISSUE THREAD

**Issue by malvinas2** [xbmc/translations#13]
What's the difference between entry 14061 and 16316? 
It is labelled with 'auto' and even the french, german and spanish translations of both entries are identical.

**Comment by ronie** [comment]
string 14061 does not exist anymore, it has been removed in kodi leia
https://github.com/xbmc/xbmc/blob/e398fc1a2c494d434d36f3f8d690308a460d511d/addons/resource.language.en_gb/resources/strings.po#L7723
