### ISSUE TITLE
Join the translation team

### ISSUE THREAD

**Issue by arialdomartini** [xbmc/translations#14]
Hi. I found some typos in the Italian translation. I'd love to contribute, and as far as I understood all the translations are handled with Transifex.

I requested to join the Italian language in the [Kodi main team](https://www.transifex.com/teamxbmc/teams/40581/) weeks ago, and got no news since then.

I would appreciate to be helped in the procedure to submit typo fixes. Thank you!

**Comment by kambala-decapitator** [comment]
I also tried to join https://www.transifex.com/teamxbmc/kodi-main/ some time ago and didn't receive any reply

**Comment by Klojum** [comment]
> Hi. I found some typos in the Italian translation. I'd love to contribute, and as far as I understood all the translations are handled with Transifex.
> 
> I requested to join the Italian language in the [Kodi main team](https://www.transifex.com/teamxbmc/teams/40581/) weeks ago, and got no news since then.
> 
> I would appreciate to be helped in the procedure to submit typo fixes. Thank you!

Unfortunately not all aspects of Kodi get the same daily attention as others for the usual reasons (time/work/family/etc), but your request has been handled and you are part of the Italian language team now.
