### ISSUE TITLE
Typo in Hungarian strings.po

### ISSUE THREAD

**Issue by musicadi** [xbmc/translations#9]
https://github.com/xbmc/translations/blob/8e74f29499b3b8655741d1caabffea72776f46a7/kodi-translations/kodi-main/merged-langfiles/kodi.core/resource.language.hu_hu/resources/strings.po#L6270

There is a typo in the above line.

I reported this a year ago on Transifex, but it's still there, so I thought I'd post it here :)

The correct string is

msgstr "Médiatár tisztítása"

**Comment by MartijnKaijser** [comment]
use transifex to fix it

**Comment by musicadi** [comment]
@MartijnKaijser Like I mentioned, I reported it through Transifex more than 1 year ago, but it was not fixed.

**Comment by MartijnKaijser** [comment]
fixed

**Comment by musicadi** [comment]
@MartijnKaijser thank you :)
